server:
  port: 8761
  servlet:
    session:
      cookie:
        name: KSESSION
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommusecase?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate : 
        show_sql : true
        format_sql : true
  application:
    name: cart-service
security:
    oauth2:
      resource:
        token-info-uri: http://localhost:8763/oauth/check_token
      client:
        client-id: mobile
        client-secret: pin
        user-authorization-uri: http://localhost:8763/oauth/authorize
        access-token-uri: http://localhost:8763/oauth/token
logging :
   level : 
    org :
       hibernate : 
          type : trace

        