spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
       bindings:
          input:
            destination: caseStudys
            group: caseStudysQueue
#  cloud:
#    stream:
#      bindings:
#           messageSourceChannel : caseStudys
           
           



           